import { useEffect, useRef, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { supabase } from '../lib/supabase'
import type { Attempt } from '../types'

export default function Exam(){
 const {attemptId=''}=useParams(), nav=useNavigate(), [attempt,setAttempt]=useState<Attempt|null>(null),[lines,setLines]=useState<NonNullable<Attempt['assigned_lines']>>([]),[now,setNow]=useState(Date.now()),[loading,setLoading]=useState(true), submitting=useRef(false), drag=useRef<number|null>(null)
 const submit=async(type='manual')=>{if(submitting.current)return;submitting.current=true; const {error}=await supabase.rpc('submit_exam',{p_attempt_id:attemptId,p_line_ids:lines.map(x=>x.id),p_submission_type:type}); if(error){submitting.current=false; alert('Submission could not be saved. Please try again.');return} sessionStorage.removeItem(`exam-lines:${attemptId}`);nav(`/result/${attemptId}`,{state:{auto:type==='auto'}})}
 useEffect(()=>{(async()=>{const {data,error}=await supabase.rpc('get_exam_attempt',{p_attempt_id:attemptId}); if(error||!data){nav('/');return}; const a=data as Attempt; if(a.submitted_at){nav(`/result/${attemptId}`);return}; const saved=JSON.parse(sessionStorage.getItem(`exam-lines:${attemptId}`)||'[]') as string[]; const restored=saved.length===a.assigned_lines.length ? saved.map(id=>a.assigned_lines.find(l=>l.id===id)).filter(Boolean) as NonNullable<Attempt['assigned_lines']> : a.assigned_lines;setAttempt(a);setLines(restored);setLoading(false)})()},[attemptId,nav])
 useEffect(()=>{if(lines.length) sessionStorage.setItem(`exam-lines:${attemptId}`,JSON.stringify(lines.map(l=>l.id)))},[attemptId,lines])
 useEffect(()=>{const tick=setInterval(()=>setNow(Date.now()),1000); const leave=()=>{if(document.visibilityState==='hidden')submit('auto')}; document.addEventListener('visibilitychange',leave); window.addEventListener('blur',leave); return()=>{clearInterval(tick);document.removeEventListener('visibilitychange',leave);window.removeEventListener('blur',leave)}},[lines])
 if(loading||!attempt)return <main className="center"><p>Loading exam…</p></main>; const elapsed=Math.max(0,Math.floor((now-new Date(attempt.started_at).getTime())/1000)), min=String(Math.floor(elapsed/60)).padStart(2,'0'),sec=String(elapsed%60).padStart(2,'0'); const move=(from:number,to:number)=>setLines(v=>{const c=[...v], [item]=c.splice(from,1);c.splice(to,0,item);return c})
 return <main className="exam"><header><div><span className="eyebrow">CODE RECONSTRUCTION</span><h2>{attempt.code_title || 'Arrange the lines'}</h2></div><strong className="timer">{min}:{sec}</strong></header><p className="muted">Drag each line into the correct position.</p><ol className="code-list">{lines.map((line,i)=><li key={line.id} draggable onDragStart={()=>drag.current=i} onDragOver={e=>e.preventDefault()} onDrop={()=>{if(drag.current!==null&&drag.current!==i)move(drag.current,i);drag.current=null}}><span className="handle" aria-label="Drag line">⠿</span><code>{line.line_text || ' '}</code></li>)}</ol><button className="submit" onClick={()=>submit()}>Submit</button></main>
}
